version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.2.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    volumes:
    - "./hasura/migrations:/hasura-migrations"
    - "./hasura/metadata:/hasura-metadata"
  bff:
    build:
      context: ./bff
      dockerfile: docker_configs/develop.Dockerfile
    image: bff-play-hasura
    tty: true
    stdin_open: true
    environment:
      GRAPHQL_ENGINE_URL: http://graphql-engine:8080/v1/graphql
      TZ: Asia/Tokyo
    ports:
     - "3000:3000"
    volumes:
      - ./bff:/usr/app
      - /usr/app/node_modules/
volumes:
  db_data:
